
package misiontic2022.view;

import java.awt.BorderLayout;
import java.awt.Color;
import java.sql.SQLException;
import java.util.List;
import javax.swing.JOptionPane;
import javax.swing.JTable;
import javax.swing.JTextField;
import javax.swing.table.AbstractTableModel;

import misiontic2022.controller.ReportesController;
import misiontic2022.model.vo.ComprasDeLiderVo;
import misiontic2022.model.vo.PagadoPorProyectoVo;
import misiontic2022.model.vo.ProyectoBancoVo;
/**
 *
 * @author Diana
 */
public class FrmVista extends javax.swing.JFrame {

    int xMouse, yMouse;
    private ReportesController reportesController;
    
    
    public FrmVista() {
        reportesController = new ReportesController();
        initComponents();
        setLocationRelativeTo(null);
    }   

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        background = new javax.swing.JPanel();
        Header = new javax.swing.JPanel();
        exitbtn = new javax.swing.JPanel();
        iconExit = new javax.swing.JLabel();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel1 = new javax.swing.JPanel();
        titulobanco = new javax.swing.JLabel();
        txtbanco = new javax.swing.JLabel();
        campotxt = new javax.swing.JTextField();
        jSeparator1 = new javax.swing.JSeparator();
        consultarbtn = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tabla = new javax.swing.JTable();
        limpiarbtnbanco = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        titulolimite = new javax.swing.JLabel();
        txtlimite = new javax.swing.JLabel();
        campotxt1 = new javax.swing.JTextField();
        jSeparator2 = new javax.swing.JSeparator();
        limitebtn = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        tablita = new javax.swing.JTable();
        limpiarbtn = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        titulolimite1 = new javax.swing.JLabel();
        liderbtn = new javax.swing.JButton();
        jScrollPane3 = new javax.swing.JScrollPane();
        tablita2 = new javax.swing.JTable();
        limpiarbtn1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setLocationByPlatform(true);
        setUndecorated(true);
        setResizable(false);

        background.setBackground(new java.awt.Color(153, 255, 255));
        background.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        Header.setBackground(new java.awt.Color(255, 255, 255));
        Header.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                HeaderMouseDragged(evt);
            }
        });
        Header.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                HeaderMousePressed(evt);
            }
        });

        exitbtn.setBackground(new java.awt.Color(255, 255, 255));
        exitbtn.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        iconExit.setFont(new java.awt.Font("Blokletters Balpen", 0, 18)); // NOI18N
        iconExit.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        iconExit.setText("X");
        iconExit.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                iconExitMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                iconExitMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                iconExitMouseExited(evt);
            }
        });

        javax.swing.GroupLayout exitbtnLayout = new javax.swing.GroupLayout(exitbtn);
        exitbtn.setLayout(exitbtnLayout);
        exitbtnLayout.setHorizontalGroup(
            exitbtnLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(iconExit, javax.swing.GroupLayout.DEFAULT_SIZE, 43, Short.MAX_VALUE)
        );
        exitbtnLayout.setVerticalGroup(
            exitbtnLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(iconExit, javax.swing.GroupLayout.DEFAULT_SIZE, 39, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout HeaderLayout = new javax.swing.GroupLayout(Header);
        Header.setLayout(HeaderLayout);
        HeaderLayout.setHorizontalGroup(
            HeaderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, HeaderLayout.createSequentialGroup()
                .addGap(0, 637, Short.MAX_VALUE)
                .addComponent(exitbtn, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        HeaderLayout.setVerticalGroup(
            HeaderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(HeaderLayout.createSequentialGroup()
                .addComponent(exitbtn, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        background.add(Header, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 680, 30));

        jTabbedPane1.setBackground(new java.awt.Color(0, 255, 255));
        jTabbedPane1.setTabPlacement(javax.swing.JTabbedPane.LEFT);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        titulobanco.setFont(new java.awt.Font("Verdana", 1, 14)); // NOI18N
        titulobanco.setText("PROYECTOS FINANCIADOS POR BANCO");

        txtbanco.setFont(new java.awt.Font("Verdana", 0, 12)); // NOI18N
        txtbanco.setText("BANCO:");

        campotxt.setFont(new java.awt.Font("Verdana", 0, 14)); // NOI18N
        campotxt.setForeground(new java.awt.Color(153, 153, 153));
        campotxt.setText("Ingresa el nombre del banco");
        campotxt.setBorder(null);
        campotxt.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                campotxtMousePressed(evt);
            }
        });
        campotxt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                campotxtActionPerformed(evt);
            }
        });

        jSeparator1.setBackground(new java.awt.Color(0, 0, 0));

        consultarbtn.setBackground(new java.awt.Color(0, 204, 204));
        consultarbtn.setFont(new java.awt.Font("Verdana", 1, 14)); // NOI18N
        consultarbtn.setForeground(new java.awt.Color(255, 255, 255));
        consultarbtn.setText("CONSULTAR");
        consultarbtn.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 204, 204), 1, true));
        consultarbtn.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        consultarbtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                consultarbtnMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                consultarbtnMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                consultarbtnMouseExited(evt);
            }
        });
        consultarbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                consultarbtnActionPerformed(evt);
            }
        });

        tabla.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null}
            },
            new String [] {
                "ID", "CONSTRUCTORA", "CIUDAD", "CLASIFICACION", "ESTRATO", "LIDER"
            }
        ));
        jScrollPane1.setViewportView(tabla);

        limpiarbtnbanco.setBackground(new java.awt.Color(51, 255, 102));
        limpiarbtnbanco.setFont(new java.awt.Font("Verdana", 1, 14)); // NOI18N
        limpiarbtnbanco.setForeground(new java.awt.Color(255, 255, 255));
        limpiarbtnbanco.setText("LIMPIAR");
        limpiarbtnbanco.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 204, 204), 1, true));
        limpiarbtnbanco.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        limpiarbtnbanco.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                limpiarbtnbancoMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                limpiarbtnbancoMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                limpiarbtnbancoMouseExited(evt);
            }
        });
        limpiarbtnbanco.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                limpiarbtnbancoActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(111, 111, 111)
                        .addComponent(titulobanco))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(24, 24, 24)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 507, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(txtbanco, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 212, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(0, 0, Short.MAX_VALUE))
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(campotxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(consultarbtn)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(limpiarbtnbanco)))))))
                .addGap(0, 0, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(titulobanco, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(consultarbtn, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtbanco, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(campotxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(limpiarbtnbanco, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 15, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 208, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Lista Por Banco", jPanel1);

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));

        titulolimite.setFont(new java.awt.Font("Verdana", 1, 14)); // NOI18N
        titulolimite.setText("LISTADO DEL TOTAL PAGADO DE CADA PROYECTO");

        txtlimite.setFont(new java.awt.Font("Verdana", 0, 12)); // NOI18N
        txtlimite.setText("LIMITE INFERIOR A:");

        campotxt1.setFont(new java.awt.Font("Verdana", 0, 14)); // NOI18N
        campotxt1.setForeground(new java.awt.Color(153, 153, 153));
        campotxt1.setText("Ingresa el valor limite");
        campotxt1.setBorder(null);
        campotxt1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                campotxt1MousePressed(evt);
            }
        });
        campotxt1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                campotxt1ActionPerformed(evt);
            }
        });

        jSeparator2.setBackground(new java.awt.Color(0, 0, 0));

        limitebtn.setBackground(new java.awt.Color(0, 204, 204));
        limitebtn.setFont(new java.awt.Font("Verdana", 1, 14)); // NOI18N
        limitebtn.setForeground(new java.awt.Color(255, 255, 255));
        limitebtn.setText("CONSULTAR");
        limitebtn.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 204, 204), 1, true));
        limitebtn.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        limitebtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                limitebtnMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                limitebtnMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                limitebtnMouseExited(evt);
            }
        });
        limitebtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                limitebtnActionPerformed(evt);
            }
        });

        tablita.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null},
                {null, null},
                {null, null},
                {null, null}
            },
            new String [] {
                "ID", "VALOR"
            }
        ));
        jScrollPane2.setViewportView(tablita);

        limpiarbtn.setBackground(new java.awt.Color(51, 255, 102));
        limpiarbtn.setFont(new java.awt.Font("Verdana", 1, 14)); // NOI18N
        limpiarbtn.setForeground(new java.awt.Color(255, 255, 255));
        limpiarbtn.setText("LIMPIAR");
        limpiarbtn.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 204, 204), 1, true));
        limpiarbtn.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        limpiarbtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                limpiarbtnMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                limpiarbtnMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                limpiarbtnMouseExited(evt);
            }
        });
        limpiarbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                limpiarbtnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(60, 60, 60)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(txtlimite, javax.swing.GroupLayout.PREFERRED_SIZE, 132, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(campotxt1, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(limitebtn))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGap(25, 25, 25)
                                .addComponent(titulolimite))))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(32, 32, 32)
                        .addComponent(limpiarbtn)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 335, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(69, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(titulolimite, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(9, 9, 9)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtlimite, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(campotxt1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(limitebtn, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 214, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(58, 58, 58)
                        .addComponent(limpiarbtn, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(10, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Lista Total Pagado", jPanel2);

        jPanel3.setBackground(new java.awt.Color(255, 255, 255));

        titulolimite1.setFont(new java.awt.Font("Verdana", 1, 14)); // NOI18N
        titulolimite1.setText("TOP 10 LIDERES QUE MENOS GASTAN EN PROYECTOS");

        liderbtn.setBackground(new java.awt.Color(0, 204, 204));
        liderbtn.setFont(new java.awt.Font("Verdana", 1, 14)); // NOI18N
        liderbtn.setForeground(new java.awt.Color(255, 255, 255));
        liderbtn.setText("CONSULTAR");
        liderbtn.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 204, 204), 1, true));
        liderbtn.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        liderbtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                liderbtnMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                liderbtnMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                liderbtnMouseExited(evt);
            }
        });
        liderbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                liderbtnActionPerformed(evt);
            }
        });

        tablita2.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null},
                {null, null},
                {null, null},
                {null, null}
            },
            new String [] {
                "LIDER", "VALOR"
            }
        ));
        jScrollPane3.setViewportView(tablita2);

        limpiarbtn1.setBackground(new java.awt.Color(51, 255, 102));
        limpiarbtn1.setFont(new java.awt.Font("Verdana", 1, 14)); // NOI18N
        limpiarbtn1.setForeground(new java.awt.Color(255, 255, 255));
        limpiarbtn1.setText("LIMPIAR");
        limpiarbtn1.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 204, 204), 1, true));
        limpiarbtn1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        limpiarbtn1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                limpiarbtn1MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                limpiarbtn1MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                limpiarbtn1MouseExited(evt);
            }
        });
        limpiarbtn1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                limpiarbtn1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(72, 72, 72)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(titulolimite1))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 435, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addGap(103, 103, 103)
                                .addComponent(liderbtn)
                                .addGap(34, 34, 34)
                                .addComponent(limpiarbtn1)))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(titulolimite1, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(liderbtn, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(limpiarbtn1, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(40, 40, 40)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 208, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(23, 23, 23))
        );

        jTabbedPane1.addTab("Lista Lideres", jPanel3);

        background.add(jTabbedPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 30, 680, 350));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(background, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(background, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        background.getAccessibleContext().setAccessibleName("");

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void iconExitMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_iconExitMouseClicked
        System.exit(0);
    }//GEN-LAST:event_iconExitMouseClicked

    private void iconExitMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_iconExitMouseEntered
        exitbtn.setBackground(Color.red);
    }//GEN-LAST:event_iconExitMouseEntered

    private void iconExitMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_iconExitMouseExited
        exitbtn.setBackground(Color.white);
    }//GEN-LAST:event_iconExitMouseExited

    private void HeaderMouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_HeaderMouseDragged
        int x =evt.getXOnScreen();
        int y =evt.getYOnScreen();
        this.setLocation(x - xMouse, y - yMouse);

    }//GEN-LAST:event_HeaderMouseDragged

    private void HeaderMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_HeaderMousePressed

        xMouse = evt.getX();
        yMouse = evt.getY();
    }//GEN-LAST:event_HeaderMousePressed

    private void campotxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_campotxtActionPerformed
        
    }//GEN-LAST:event_campotxtActionPerformed

    private void consultarbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_consultarbtnActionPerformed
        
    }//GEN-LAST:event_consultarbtnActionPerformed

    private void consultarbtnMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_consultarbtnMouseEntered
        consultarbtn.setBackground(new Color(0,255,255));
    }//GEN-LAST:event_consultarbtnMouseEntered

    private void consultarbtnMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_consultarbtnMouseExited
        consultarbtn.setBackground(new Color(0,204,204));
    }//GEN-LAST:event_consultarbtnMouseExited

    private void consultarbtnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_consultarbtnMouseClicked
        consultarbtn.addActionListener(e -> consultarProyectosPorBanco(campotxt.getText().trim()));
    }//GEN-LAST:event_consultarbtnMouseClicked

    private void campotxtMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_campotxtMousePressed
        if(campotxt.getText().equals("Ingresa el nombre del banco")){
           campotxt.setText("                    ");
           campotxt.setForeground(Color.black);
        }

        
  
    }//GEN-LAST:event_campotxtMousePressed

    private void campotxt1MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_campotxt1MousePressed
        if(campotxt1.getText().equals("Ingresa el valor limite")){
           campotxt1.setText("              ");
           campotxt1.setForeground(Color.black);
        }
    }//GEN-LAST:event_campotxt1MousePressed

    private void campotxt1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_campotxt1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_campotxt1ActionPerformed

    private void limitebtnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_limitebtnMouseClicked
        limitebtn.addActionListener(e ->{
            var captura =campotxt1.getText(); 
            double convertido = Double.valueOf(captura);
            consultarProyectosPorPago(convertido);});
    }//GEN-LAST:event_limitebtnMouseClicked

    private void limitebtnMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_limitebtnMouseEntered
        limitebtn.setBackground(new Color(0,255,255));
    }//GEN-LAST:event_limitebtnMouseEntered

    private void limitebtnMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_limitebtnMouseExited
        limitebtn.setBackground(new Color(0,204,204));
    }//GEN-LAST:event_limitebtnMouseExited

    private void limitebtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_limitebtnActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_limitebtnActionPerformed

    private void liderbtnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_liderbtnMouseClicked
        liderbtn.addActionListener(e ->consultarPorLider());
    }//GEN-LAST:event_liderbtnMouseClicked

    private void liderbtnMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_liderbtnMouseEntered
       liderbtn.setBackground(new Color(0,255,255));
    }//GEN-LAST:event_liderbtnMouseEntered

    private void liderbtnMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_liderbtnMouseExited
        liderbtn.setBackground(new Color(0,204,204));
    }//GEN-LAST:event_liderbtnMouseExited

    private void liderbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_liderbtnActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_liderbtnActionPerformed

    private void limpiarbtnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_limpiarbtnMouseClicked
        tablita.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null,null},
                {null, null, null, null,null}
                
            },
            new String [] {
                "ID", "VALOR",
            }));
    }//GEN-LAST:event_limpiarbtnMouseClicked

    private void limpiarbtnMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_limpiarbtnMouseEntered
        limpiarbtn.setBackground(new Color(102,255,102));
    }//GEN-LAST:event_limpiarbtnMouseEntered

    private void limpiarbtnMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_limpiarbtnMouseExited
        limpiarbtn.setBackground(new Color(51,255,102));
    }//GEN-LAST:event_limpiarbtnMouseExited

    private void limpiarbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_limpiarbtnActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_limpiarbtnActionPerformed

    private void limpiarbtn1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_limpiarbtn1MouseClicked
        tablita2.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null,null},
                {null, null, null, null,null}
                
            },
            new String [] {
                "LIDER", "VALOR",
            }));
    }//GEN-LAST:event_limpiarbtn1MouseClicked

    private void limpiarbtn1MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_limpiarbtn1MouseEntered
        limpiarbtn1.setBackground(new Color(102,255,102));
    }//GEN-LAST:event_limpiarbtn1MouseEntered

    private void limpiarbtn1MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_limpiarbtn1MouseExited
        limpiarbtn1.setBackground(new Color(51,255,102));
    }//GEN-LAST:event_limpiarbtn1MouseExited

    private void limpiarbtn1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_limpiarbtn1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_limpiarbtn1ActionPerformed

    private void limpiarbtnbancoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_limpiarbtnbancoMouseClicked
        tabla.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null,null},
                {null, null, null, null,null}
                
            },
            new String [] {
                "ID", "CONSTRUCCION", "CIUDAD","CLASIFICACION","ESTRATO","LIDER"
            }));
    }//GEN-LAST:event_limpiarbtnbancoMouseClicked

    private void limpiarbtnbancoMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_limpiarbtnbancoMouseEntered
        limpiarbtnbanco.setBackground(new Color(102,255,102));
    }//GEN-LAST:event_limpiarbtnbancoMouseEntered

    private void limpiarbtnbancoMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_limpiarbtnbancoMouseExited
       limpiarbtnbanco.setBackground(new Color(51,255,102));
    }//GEN-LAST:event_limpiarbtnbancoMouseExited

    private void limpiarbtnbancoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_limpiarbtnbancoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_limpiarbtnbancoActionPerformed
    
  
    
    private void consultarProyectosPorBanco(String banco) {
        try {
            var lista = reportesController.listarProyectosPorBanco(banco);
            var tableModel = new FrmVista.laTableModel();
            tableModel.setData(lista);

            tabla.setModel(tableModel);
        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(this, ex.getMessage(), getTitle(), JOptionPane.ERROR_MESSAGE);
        }
    }
    private class laTableModel extends AbstractTableModel {
        private List<ProyectoBancoVo> data;

        public void setData(List<ProyectoBancoVo> data) {
            this.data = data;
        }

        @Override
        public Class<?> getColumnClass(int columnIndex) {
            switch (columnIndex) {
                case 1:
                case 2:
                case 3:
                case 5:
                    return String.class;
                case 0:
                case 4:
                    return Integer.class;
            }
            return super.getColumnClass(columnIndex);
        }

        @Override
        public String getColumnName(int column) {
            switch (column) {
                case 0:
                    return "ID";
                case 1:
                    return "CONSTRUCTORA";
                case 2:
                    return "CIUDAD";
                case 3:
                    return "CLASIFICACION";
                case 4:
                    return "ESTRATO";
                case 5:
                    return "LIDER";
            }
            return super.getColumnName(column);
        }

        @Override
        public int getRowCount() {
            return data.size();
        }

        @Override
        public int getColumnCount() {
            return 6;
        }

        @Override
        public Object getValueAt(int rowIndex, int columnIndex) {
            var project = data.get(rowIndex);
            switch (columnIndex) {
                case 0:
                    return project.getId();
                case 1:
                    return project.getConstructora();
                case 2:
                    return project.getCiudad();
                case 3:
                    return project.getClasificacion();
                case 4:
                    return project.getEstrato();
                case 5:
                    return project.getLider();
            }
            return null;
        }
    }
    
    
    private void consultarProyectosPorPago(Double limiteInferior){

        try {
            var lista = reportesController.listarPagadoPorProyecto(limiteInferior);
            var tableModel = new ProyectosTableModel2();
            tableModel.setData(lista);

            tablita.setModel(tableModel);
        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(this, ex.getMessage(), getTitle(), JOptionPane.ERROR_MESSAGE);
        }

    }
    private class ProyectosTableModel2 extends AbstractTableModel{
         private List<PagadoPorProyectoVo> data;

        public void setData(List<PagadoPorProyectoVo> data) {
            this.data = data;
        }

        @Override
        public Class<?> getColumnClass(int columnIndex) {
            switch (columnIndex) {
                case 0:
                    return String.class;
                case 1:
                    return Double.class;
            }
            return super.getColumnClass(columnIndex);
        }

        @Override
        public String getColumnName(int column) {
            switch (column) {
                case 0:
                    return "ID";
                case 1:
                    return "VALOR";
            }
            return super.getColumnName(column);
        }

        @Override
        public int getRowCount() {
            return data.size();
        }

        @Override
        public int getColumnCount() {
            return 2;
        }

        @Override
        public Object getValueAt(int rowIndex, int columnIndex) {
            var project = data.get(rowIndex);
            switch (columnIndex) {
                case 0:
                    return project.getId();
                case 1:
                    return project.getValor();
            }
            return null;
        }
    }
    
    private void consultarPorLider(){
        try {
            var lista = reportesController.listarLideresQueMenosGastan();
            var tableModel = new ProyectorTableModel3();
            tableModel.setData(lista);

            tablita2.setModel(tableModel);
        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(this, ex.getMessage(), getTitle(), JOptionPane.ERROR_MESSAGE);
        }
    }

    private class ProyectorTableModel3 extends AbstractTableModel{
        private List<ComprasDeLiderVo> data;

        public void setData(List<ComprasDeLiderVo> data) {
            this.data = data;
        }

        @Override
        public Class<?> getColumnClass(int columnIndex) {
            switch (columnIndex) {
                case 0:
                    return String.class;
                case 1:
                    return Double.class;
            }
            return super.getColumnClass(columnIndex);
        }

        @Override
        public String getColumnName(int column) {
            switch (column) {
                case 0:
                    return "LIDER";
                case 1:
                    return "VALOR";
            }
            return super.getColumnName(column);
        }

        @Override
        public int getRowCount() {
            return data.size();
        }

        @Override
        public int getColumnCount() {
            return 2;
        }

        @Override
        public Object getValueAt(int rowIndex, int columnIndex) {
            var project = data.get(rowIndex);
            switch (columnIndex) {
                case 0:
                    return project.getId();
                case 1:
                    return project.getValor();
            }
            return null;
        }
    }
    
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FrmVista.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FrmVista.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FrmVista.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FrmVista.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FrmVista().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel Header;
    private javax.swing.JPanel background;
    private javax.swing.JTextField campotxt;
    private javax.swing.JTextField campotxt1;
    private javax.swing.JButton consultarbtn;
    private javax.swing.JPanel exitbtn;
    private javax.swing.JLabel iconExit;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JButton liderbtn;
    private javax.swing.JButton limitebtn;
    private javax.swing.JButton limpiarbtn;
    private javax.swing.JButton limpiarbtn1;
    private javax.swing.JButton limpiarbtnbanco;
    public javax.swing.JTable tabla;
    private javax.swing.JTable tablita;
    private javax.swing.JTable tablita2;
    private javax.swing.JLabel titulobanco;
    private javax.swing.JLabel titulolimite;
    private javax.swing.JLabel titulolimite1;
    private javax.swing.JLabel txtbanco;
    private javax.swing.JLabel txtlimite;
    // End of variables declaration//GEN-END:variables
}
